### ISSUE TITLE
What is difference between "nonces" and "seals"?

### ISSUE THREAD

**Issue by Sinjir** [nervosnetwork/ckb-cuckoo-miner#15]
Hi,
I used official ckb for 1 cpu thread with "ckb.exe miner" command. This was it's output:
**hashrate: 241765  /  nonces found:  0**

then I used this program and It's output was:
**hashrate: 4017520  /  seals found:  0**

Both programs runned on MIANNET.
What is difference between "nonces" and "seals"?
Why Hashrates is so difference?
Can I use this program for MAINNET solo mining?

**Comment by kilb** [comment]
It is same
