### ISSUE TITLE
GTX1060. Gpu Miner可以运行但cycles found = 0。

### ISSUE THREAD

**Issue by 1178209138** [nervosnetwork/ckb-cuckoo-miner#2]
显示gps：15000（左右） /cycles found :     0。

ckb-miner.toml设置：
# the gpu you want to use runing miner, can be 0,1,2,3,..
# only work if a gpu miner was built in.
gpus     = [1]

# how many cpu miners you want to run
cpus = 2

**Comment by wangke0809** [comment]
说明你没挖到矿呀，是正常的，等等看，现在难度已经上去了。

**Comment by sherlockhouse** [comment]
配置如下，同样cycles found 一直是0

# Config generated by `ckb init --chain testnet`

data_dir = "data"

[chain]
# Choose the kind of chains to run, possible values:
# - { file = "specs/dev.toml" }
# - { bundled = "specs/testnet.toml" }
spec = { bundled = "specs/testnet.toml" }

[logger]
filter = "info"
color = true
log_to_file = true
log_to_stdout = true

[sentry]
# set to blank to disable sentry error collection
dsn = "https://48c6a88d92e246478e2d53b5917a887c@sentry.io/1422795"
# if you are willing to help us to improve,
# please leave a way to contact you when we have troubles to reproduce the errors.
# org_contact = ""


[miner]
rpc_url = "http://127.0.0.1:8114/"
block_on_submit = true

# block template polling interval in milliseconds
poll_interval = 1000

# the gpu you want to use runing miner, can be 0,1,2,3,..
# only work if a gpu miner was built in.
gpus     = [0]

# how many cpu miners you want to run
cpus = 2

**Comment by 1178209138** [comment]
> 说明你没挖到矿呀，是正常的，等等看，现在难度已经上去了。

不是没挖到，cycles found是会一直增加的，而它等于0表示程序未正常运行，挖到了是显示如seal found：1.

**Comment by yulidai** [comment]
我编译完后, 配置为:
```
gpus = [1]
cpus = 1
```

运行后是这样的:
```
Cuckoo-Worker-GPU-1 ⠁ [00:00:00]
Cuckoo-Worker-CPU-0 ⠠ [00:01:36] gps:   1163.397 / seals found:          0
```

似乎 GPU 并未挖

**Comment by wangke0809** [comment]
> 我编译完后, 配置为:
> 
> ```
> gpus = [1]
> cpus = 1
> ```
> 
> 运行后是这样的:
> 
> ```
> Cuckoo-Worker-GPU-1 ⠁ [00:00:00]
> Cuckoo-Worker-CPU-0 ⠠ [00:01:36] gps:   1163.397 / seals found:          0
> ```
> 
> 似乎 GPU 并未挖

如果只有 1 个 GPU，应该是 gpus = [0]

**Comment by yulidai** [comment]
结果是一样的~

**Comment by yulidai** [comment]
```
ld@solana:~/ckb-cuckoo-miner$ nvidia-smi
Tue Aug 13 16:32:57 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.74       Driver Version: 418.74       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:09:00.0 Off |                  N/A |
| 30%   53C    P0    54W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:41:00.0 Off |                  N/A |
| 35%   51C    P0     1W / 250W |      0MiB / 10989MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

ld@solana:~/ckb-cuckoo-miner$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105
```

**Comment by yulidai** [comment]
运行后  的确有用到显卡:
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0    103647      C   ./ckb-miner                                 2209MiB |
+-----------------------------------------------------------------------------+
```

但进度条为啥没反应呢~

**Comment by yulidai** [comment]
看了下  应该是执行了 `c_solve_gpu` 函数后就再也没返回了~

**Comment by megazone87** [comment]
> 看了下 应该是执行了 `c_solve_gpu` 函数后就再也没返回了~

有进展了么，我跟你一样的现象，我是centos7

**Comment by yulidai** [comment]
@songmeixu  可能我测试的显卡太新的  用老一点的可以

**Comment by kilb** [comment]
There is a bug on Nvidia 20 series GPUs, we are working on it.

**Comment by kilb** [comment]
Here the "cycles found" means "seals found", different with "ckb miner".

**Comment by 1178209138** [comment]
Ths
