### ISSUE TITLE
Win10--error: build failed

### ISSUE THREAD

**Issue by 1178209138** [nervosnetwork/ckb-cuckoo-miner#6]
error: failed to run custom build command for `miner v0.18.0 (E:\ckb-cuckoo-miner-0.18.0\miner)`

Caused by:
  process didn't exit successfully: `E:\ckb-cuckoo-miner-0.18.0\target\release\build\miner-1813ef1cc1448ac9\build-script-build` (exit code: 1)
--- stderr

error occurred: Command "E:\\VS2017\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-static" "-I" "src/worker/include" "-W4" "-O3" "-lcrypto" "-mavx512f" "-mavx512cd" "-msse4" "-FoE:\\ckb-cuckoo-miner-0.18.0\\target\\release\\build\\miner-9b4481fa7ed5743d\\out\\src/worker/include\\cuckoo-avx512.o" "-c" "src/worker/include/cuckoo-avx512.c" with args "cl.exe" did not execute successfully (status code exit code: 2).

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by 1178209138** [comment]
Environment：
OS:Win10、CUDA:10.1、Nvidia driver 436.02、VS2017

**Comment by kilb** [comment]
You build wrong code, if you want to build v0.18 in windows, you should use the branch win/v0.18.0.

**Comment by 1178209138** [comment]
Thanks for your reply.It solved my problem.
